QuTech-Delft/qx-simulator

.gitmodules

libqasm submodule url has been changed to https://github.com/QE-Lab/qx-simulator.git to avoid failing CI

updated libqasm submodule url to avoid failing CI

---

src/xpu-0.1.5/xpu/core/generic_worker.h

This works around the occasional `thread::start() : pthread_setaffinity_np() failed` exception that's been plaguing the Quantum Inspire team. The exception most likely occurs because `m_cpu` is only initialized when `set_cpu()` is first called and thus might contain garbage for some code paths, or perhaps because `set_cpu()` is called with garbage. I just tore out the entire processor affinity call; it really shouldn't functionally matter what processor a thread runs on, and in terms of performance I doubt this would actually have helped, considering the state of the codebase.

"Fix" pthread_setaffinity errors

---

CMakeLists.txt
qxelarator/qxelarator/qx_simulator.h
src/CMakeLists.txt
src/core/gate.h
src/core/register.cc
src/simulator.cc
src/xpu-0.1.5/xpu/complex.h

Hi there, 
I'm working with `qx-simulator` at SURF and got some additions/improvements to the `without-xpu` branch. Those are related to:
- better parallelization of the OMP parallel regions
- basic improvement of the memory allocation following the "first-touch" policy
- additional AVX512 support for `renorm_worker()` function
- minor improvement over the branch prediction in `zero_worker()` function
- minor improvement of the `xpu::complex_d::norm()` method
- enhancement of the `CMakeLists` to work with Intel compilers and `gperftools`
Please, take a look and let me know if you find them useful.

Optimised OMP parallel regions, minor improvements

---

.github/workflows/assets.yml
.github/workflows/test.yml
CMakeLists.txt
README.md
include/qx/version.h
setup.py

At least the Linux wheels generated by CI don't work on my pretty recent machine, so I imagine it wouldn't work on many other PCs either. In general it makes no sense to optimize PyPI wheels for the GitHub runner that happens to be building them.

Build using at most SSE3 instructions on CI

---

.github/workflows/assets.yml
.github/workflows/test.yml
include/qx/libqasm_interface.h

Basically, just ignore barriers when they appear. Same for wait and skip instructions, which gave an internal error before.

Add support for barriers

---

.github/workflows/assets.yml
.github/workflows/test.yml
CHANGELOG.md
include/qx/simulator.h
include/qx/version.h
setup.py

- "-j <filename>" CLI option to output JSON to a file
- Possible to use the simulator without OpenMP.
- Measure_all gate added; does no longer measure each qubit separately.
- Move to C++11: smart pointers, etc.
- Format of output has been changed. You no longer need to add a "display" gate to
output the quantum state at the end of the circuit.
- Now uses the new Libqasm API instead of the old one.
- Most preprocessor macros. E.g. for gate creation.
- A lot of old and useless code was removed. A lot of dead code removed.
- Close input file when done.
- Code style has been completely fixed automatically with clang-format.
- Headers no longer include .cc file.
- Moved implementations to .cc files instead of headers.

Release version 0.5.0

---

setup.py

Fix setup.py not actually using environment variable value
The CMake option QX_CPU_COMPATIBILITY_MODE is by default ON. It was not possible to set it to OFF using environment variables.

Make it possible to unset QX_CPU_COMPATIBILITY_MODE when building Python package 

---

CHANGELOG.md
include/qx/Core.hpp
include/qx/Qxelarator.hpp
include/qx/Simulator.hpp
include/qx/Version.hpp
python/Qxelarator.i
src/qx-simulator/Simulator.cpp
src/qx/Simulator.cpp
tests/IntegrationTest.cpp
tests/qxelarator/test_Qxelarator.py

- Do not crash when too many qubits
- Return meaningful error message in SimulationError Python type (errors coming from libqasm and from the simulator itself)
Those two behaviours are very much desired for the tutorial.

Release 0.6.4

---

.github/workflows/test.yml
CMakeLists.txt
conan/profiles/debug
conan/profiles/release
conan/profiles/tests-debug
conan/profiles/tests-release
conanfile.py
setup.py

Update `conanfile.py` to:
- request `libqasm/0.6.5`, and
- use `tools.build.skip_test`, instead of `qx/*:build_tests`.
Update `CMakeLists.txt` to:
- `find_package(libqasm)`, and
- link against `libqasm::libqasm`.
Update GitHub workflows with some improvements taken from `libqasm`.

Update to use `libqasm` Conan package

---

CMakeLists.txt
conan/profiles/base
conan/profiles/debug
conan/profiles/release
conan/profiles/tests-debug
conan/profiles/tests-release
conanfile.py
include/qx/CompileTimeConfiguration.hpp
include/qx/Core.hpp
include/qx/Instructions.hpp
include/qx/QuantumState.hpp
include/qx/RegisterManager.hpp
include/qx/SimulationResult.hpp
include/qx/V3xLibqasmInterface.hpp
setup.py
src/qx/GateConvertor.cpp
src/qx/InstructionExecutor.cpp
src/qx/OperandsHelper.cpp
src/qx/QuantumState.cpp
src/qx/RegisterManager.cpp
src/qx/SimulationResult.cpp
src/qx/Simulator.cpp
src/qx/V3xLibqasmInterface.cpp
test/ErrorModelsTest.cpp
test/IntegrationTest.cpp
test/QuantumStateTest.cpp

With the introduction of bit (register) variables in the language and in the libqasm parser (mainly due to the introduction of the `measure` intruction with the form `<bit-side> = measure <qubit-side>`), the QX simulator has to be updated to support bit (register) variables.
It turns out that this opens a big discussion (see this [Confluence page](https://qutech-sd.atlassian.net/wiki/spaces/QW/pages/3500277765/Proposal+SimulationResult+format)) because, once you have multiple qubit and bit registers, and you can measure a given qubit to different bit registers, and, basically, you don’t have anymore a 1-to-1 correspondence between qubits and bits -here we should ask ourselves, wait, what qubits anyway? because once you have qubit (register) variables you don’t have either a single qubit …

[CQT-26] Manage bit (register) variables

---

include/qx/Circuit.hpp
include/qx/InstructionExecutor.hpp
include/qx/QuantumState.hpp
src/qx/Circuit.cpp
src/qx/InstructionExecutor.cpp
src/qx/QuantumState.cpp
src/qx/Simulator.cpp
test/QuantumStateTest.cpp

While making this refactoring I've noticed there is room for quite some more changes.
So I intend this to be the first of a series of mini refactorings.
However, up to this point, we have what we pretended: taking the measurement register out of the QuantumState.
- Add measurement register to InstructionExecutor.
- Add measurement register to Circuit::execute.
- Add measurement register to QuantumState::measure.
- Rename some variables.

[CQT-130] Take measurement register out of QuantumState

---

CHANGELOG.md
include/qx/Circuit.hpp
include/qx/InstructionExecutor.hpp
include/qx/QuantumState.hpp
include/qx/SimulationResult.hpp
include/qx/Simulator.hpp
src/qx/Circuit.cpp
src/qx/InstructionExecutor.cpp
src/qx/QuantumState.cpp
src/qx/SimulationResult.cpp
src/qx/Simulator.cpp

The `SimulationIterationResult` holds:
- a quantum state,
- a measurement register, and
- a bit measurement register.
The `InstructionExecutor` holds a simulation iteration result.
The `execute` function at Simulator.cpp is simplified to:
- accumulating the simulation iteration results of executing a circuit, and then
- returning the final simulation result.

[CQT-274] Change `Circuit::execute` to return `SimulationIterationResult`

---

CHANGELOG.md
CMakeLists.txt
conanfile.py
include/qx/cqasm_v3x.hpp
include/qx/simulation_result.hpp
include/qx/sparse_array.hpp
src/qx/simulator.cpp
src/qx/sparse_array.cpp

Remove `abseil` dependency:
- Use `std::map` instead of `absl::btree_map`.
- Use `std::unordered_map` instead of `absl::flat_hash_map`.
- Move `CqasmV3xAnalysisResult` from simulator.cpp to cqasm_v3x.hpp.
Update CHANGELOG.md.

[CQT-292] Remove `abseil` dependency

---

.github/workflows/assets.yaml
CHANGELOG.md
include/qx/version.hpp

- Documentation: GitHub pages.
- Linters: `.clang-format` and `.clang-tidy`.
- Integrate with libqasm 0.6.8 release:
- Add gate modifiers. Notice though that `pow` only works with integer exponents.
- Implement instructions as a hierarchy.
- Implement `GateConvertor` as a `CircuitBuilder`.
- Implement `BasisVector` as a `boost::dynamic_bitset<uint32_t>`.
- Implement `RegisterManager` as a singleton.
- Change `QuantumState` by taking the measurement register out of it.
- Change `Circuit::execute` to return a `SimulationIterationContext`.
- Change `Matrix` and `DenseUnitaryMatrix` to use `std::vector` instead of `std::array`.
- Change file, functions, and variable names.
- `abseil` library dependency.

Creating release 0.7.3.

---

CHANGELOG.md
conanfile.py
include/qx/instructions.hpp
include/qx/register_manager.hpp
src/qx/circuit.cpp
src/qx/circuit_builder.cpp
src/qx/instructions.cpp
src/qx/register_manager.cpp
test/integration_test.cpp

Update the simulator to correctly work with libQASM 0.6.9.
libQASM 0.6.9 adds:
- `SWAP` gate instruction. Which is already implemented in QX simulator.
- `barrier`, `wait`, and `init` non-gate instructions.
The register manager now holds a 'dirty bitset' for virtual qubit and bit indices:
- All instructions added to the circuit set dirty flags for each qubit operand.
- Notice 'barrier', 'wait', and 'init' are not added to the circuit.
- 'init' instructions throw if they are performed on a 'dirty' qubit.
`wait` instructions throw if they time parameter is negative.

Integrate libQASM 0.6.9 into QX simulator

---

CHANGELOG.md
include/qx/version.hpp

- Integrate with libqasm 0.6.9 release:
- Add `SWAP` gate instruction.
- Add `barrier`, `wait`, and `ìnit` non-gate instructions.
- The register manager now holds a 'dirty bitset' for virtual qubit and bit indices.

Creating release 0.7.4

---

.github/workflows/doc.yaml
CHANGELOG.md
requirements.txt

I have just  noticed this wasn't added when we added the documentation framework (QX/0.7.3).
We need a `doc` GitHub Actions workflow to build and publish an updated documentation.

Add `doc` workflow

---

CHANGELOG.md
include/qx/simulation_result.hpp
python/qxelarator/__init__.py
src/qx/simulation_result.cpp
src/qx/simulator.cpp

Update SimulationIterationAccumulator:
- `get_simulation_result` now receives `shots_requested`.
- Add `shots_done`.
- Remove `measurements_count` and `bit_measurements_count`.
Update SimulationResult Python documentation:
- `shots_requested` is the number of requested iterations.
- `shots_done` is the number of performed iterations.

[CQT-305] Check if `shots_done` can be removed

---

CHANGELOG.md
include/qx/dense_unitary_matrix.hpp
include/qx/gates.hpp
src/qx/dense_unitary_matrix.cpp
test/dense_unitary_matrix.cpp

Allow move constructing a `DenseUnitaryMatrix`.
Change `DenseUnitaryMatrix` constructor to receive a unitary check flag.
Add default constructors and assignment operators for `DenseUnitaryMatrix`.
Change all default gate definitions to inline.
Do not check if a matrix is unitary for default gates.

[CQT-321] Optimizations to `DenseUnitaryMatrix` and default gates

---

conan/profiles/debug
conan/profiles/tests-debug
conan/profiles/tests-debug-clang-linux-arm64
conan/profiles/tests-debug-clang-linux-x64

It seems we can enable address sanitizer for the debug builds except for the `clang` compiler.
We could at least merge these changes, close the issue, and open a new issue focused on fixing the address sanitizer for `clang` builds.
The "good" side of these address sanitizer problems is that:
1. They seem to have to do with gtest, and not with our code.
2. Thy seem to be kind of secondary, i.e., not memory leaks, or misuse of pointers, and so on. For example, for `clang` builds, the address sanitizer complains of memory being allocated with `new` and released with `free`.

[CQT-344] Fix issue #135

---

.github/workflows/test.yaml

Disable temporarily.
Until an antlr4-cppruntime>4.13.1 Conan package builds in Windows/Debug.

Disable Windows/Debug job.

---

CHANGELOG.md
include/qx/version.hpp

- Integrate with libqasm 1.1.0 release.
- `pow` gate modifier now works with fractional exponents.

Creating release 0.8.0

---

CHANGELOG.md
include/qx/gates.hpp
python/CMakeLists.txt
test/dense_unitary_matrix.cpp
test/integration_test.cpp

Update definition of gates X90, Y90, Z90, MX90, MY90, and MZ90.
Add control_gate_modifier__ctrl_x90 and control_gate_modifier__ctrl_rx_half_pi integration tests.

[CQT-356] Pi-half rotation gates defined incorrectly

---

CHANGELOG.md
include/qx/quantum_state.hpp
include/qx/simulation_result.hpp
include/qx/sparse_array.hpp
src/qx/simulation_result.cpp
src/qx/sparse_array.cpp
test/integration_test.cpp

The problem came from `SparseComplex::operator=`, which was not always performing the assignment (only when a check was true, and that check was wrong).
Implement `operator<<` for `qx::Measurement` and `qx::SuperposedState`.
Add `fmt::formatter`s for `qx::Measurement` and `qx::SuperposedState`.
Remove rule of 5 for SparseComplex.
Remove `SparseArray::operator=(MapBasisVectorToSparseComplex)`.

[CQT-360] QX simulator outputs invalid states
